name: moneytrace
description: "Paraİz (MoneyTrace) - Deterministik Veri Motoru & Harcama Zekası Platformu"
publish_to: 'none'
version: 3.7.1+7

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Grafikler
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1

  # Yerel Depolama & Veritabanı
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0

  # PDF Okuma & Güvenlik
  file_picker: ^8.0.5
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # Yardımcı & Biçimlendirme
  intl: ^0.20.3
  share_plus: ^10.0.0
  url_launcher: ^6.3.0

  # Google Play Billing & Widget
  in_app_purchase: ^3.2.0
  home_widget: ^0.6.0
  flutter_secure_storage: ^10.3.4
  flutter_local_notifications: ^22.3.1
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  pdfrx: ^2.6.5
  pdfrx_engine: ^0.6.1
  in_app_purchase_android: 0.5.3
  supabase_flutter: ^2.17.2
  google_sign_in: ^7.2.0
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dictionaries/
    - assets/sql/
    - assets/config/
    - assets/banks/
